# Generated by Django 2.2.4 on 2019-09-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='us_staff',
            new_name='is_staff',
        ),
    ]
